# Generated by Django 6.0.2 on 2026-04-17 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_bot_last_execution_denorm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='silence_threshold_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('silent_bot', 'Bot silencioso'), ('error_spike', 'Pico de erros'), ('heartbeat_lost', 'Heartbeat perdido'), ('duration_regression', 'Regressão de duração')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', max_length=10)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botapp_acked_alerts', to=settings.AUTH_USER_MODEL)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='botapp.bot')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botapp_resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'indexes': [models.Index(fields=['-created_at'], name='alert_created_desc_idx'), models.Index(fields=['bot', 'type', 'resolved_at'], name='alert_bot_type_res_idx')],
            },
        ),
    ]
