# Generated by Django 5.2.15 on 2026-08-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_bot_silence_threshold_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gitlab', 'GitLab')], default='gitlab', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='URL do servidor de CI. Sem default de propósito.')),
                ('namespace', models.CharField(help_text='Grupo/organização a sincronizar (path ou id numérico).', max_length=255)),
                ('token_source', models.CharField(choices=[('env', 'Variável de ambiente (recomendado)'), ('db', 'Cifrado no banco')], default='env', max_length=10)),
                ('token_env_var', models.CharField(blank=True, default='BOTAPP_CI_TOKEN', help_text='Nome da env var com o token (quando a fonte é ambiente).', max_length=100)),
                ('token_encrypted', models.BinaryField(blank=True, help_text='Só usado quando a fonte é banco; exige BOTAPP_CI_TOKEN_KEY.', null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('discovery_interval_minutes', models.PositiveIntegerField(default=1440)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=15)),
                ('last_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Erro'), ('never', 'Nunca sincronizado')], default='never', max_length=10)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conexão de CI',
                'verbose_name_plural': 'Conexões de CI',
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('silent_bot', 'Bot silencioso'), ('error_spike', 'Pico de erros'), ('heartbeat_lost', 'Heartbeat perdido'), ('duration_regression', 'Regressão de duração'), ('pipeline_failed', 'Pipeline falhou'), ('pipeline_masked_error', 'Pipeline verde com erro no log'), ('schedule_without_run', 'Agendamento ativo sem execução'), ('project_never_ran', 'Projeto monitorado sem execução')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='CIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('web_url', models.URLField(blank=True, default='')),
                ('default_branch', models.CharField(blank=True, default='', max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('monitored', models.BooleanField(db_index=True, default=True, help_text='Projeto monitorado tem pipelines sincronizados.')),
                ('scan_logs', models.BooleanField(default=False, help_text='Procura padrão de erro no log de pipeline BEM-SUCEDIDO (detecta "verde que mente"). Custa uma chamada por job.')),
                ('pipelines_cursor', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('last_pipeline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_pipeline_status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('last_pipeline_external_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, help_text='Vínculo com o bot instrumentado pelo SDK, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_projects', to='botapp.bot')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='botapp.ciconnection')),
            ],
            options={
                'verbose_name': 'Projeto de CI',
                'verbose_name_plural': 'Projetos de CI',
            },
        ),
        migrations.CreateModel(
            name='CISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cron', models.CharField(blank=True, default='', max_length=100)),
                ('cron_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_pipeline_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='botapp.ciproject')),
            ],
            options={
                'verbose_name': 'Agendamento de CI',
                'verbose_name_plural': 'Agendamentos de CI',
            },
        ),
        migrations.CreateModel(
            name='CIPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True)),
                ('iid', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('ref', models.CharField(blank=True, default='', max_length=255)),
                ('sha', models.CharField(blank=True, default='', max_length=64)),
                ('commit_title', models.CharField(blank=True, default='', max_length=255)),
                ('web_url', models.URLField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('log_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('has_masked_error', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='botapp.ciproject')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='botapp.cischedule')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
            },
        ),
        migrations.CreateModel(
            name='CIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('runner_description', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=100)),
                ('web_url', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('log_excerpt', models.TextField(blank=True, default='')),
                ('log_excerpt_at', models.DateTimeField(blank=True, null=True)),
                ('matched_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='botapp.cipipeline')),
            ],
            options={
                'verbose_name': 'Job de CI',
                'verbose_name_plural': 'Jobs de CI',
                'unique_together': {('pipeline', 'external_id')},
            },
        ),
        migrations.AddIndex(
            model_name='ciproject',
            index=models.Index(fields=['monitored', '-last_pipeline_at'], name='ciproj_mon_last_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ciproject',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cischedule',
            unique_together={('project', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='cipipeline',
            index=models.Index(fields=['-created_at'], name='cipipe_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='cipipeline',
            index=models.Index(fields=['project', '-created_at'], name='cipipe_proj_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cipipeline',
            unique_together={('project', 'external_id')},
        ),
    ]
