# Generated by Django 5.2.15 on 2026-08-18 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_ciconnection_alter_alert_type_ciproject_cischedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ciproject',
            name='local_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ciproject',
            name='local_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciproject',
            name='local_archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botapp_archived_ci_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciproject',
            name='local_archived_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
